version: '2.4'
services:
  wwwserver:
    build: .
    image: asn/phpwebapp
    ports:
      # Random external port for HTTP direct access 
      - "80"

    # amount of replicas of this service
    scale: 4

    # limit memory for testing
    mem_limit: 50m
    mem_reservation: 25m
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb 
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=notesdb
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=secreto
    ports:
      - 3306:3306
  nginx:
    image: asn/nginx
    build: ../loadbalancer/nginx/
    ports:
      - "8000:80"
    depends_on:
      - wwwserver #nginx needs all servers available
    volumes:
      # NGinx static config file
      - ../loadbalancer/nginx/nginx.conf:/etc/nginx/nginx.conf
