version: '2.4'
services:
  wwwserver:
    build: .
    image: asn/djangowebapp
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      # Random external port for HTTP direct access 
      - "80"

    # amount of replicas of this service
    scale: 4

    # limit memory for testing
    mem_limit: 50m
    mem_reservation: 25m

  nginx:
    image: asn/nginx
    build: ../loadbalancer/nginx/
    ports:
      - "8000:80"
    depends_on:
      - wwwserver #nginx needs all servers available
    volumes:
      # NGinx static config file
      - ../loadbalancer/nginx/nginx_asn_web_security.conf:/etc/nginx/nginx.conf
